[{'accept_incomplete_resumes': False,
  'accept_temporary': False,
  'address': None,
  'adv_context': None,
  'adv_response_url': None,
  'alternate_url': 'https://hh.ru/vacancy/120111330',
  'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=120111330',
  'archived': False,
  'area': {'id': '160', 'name': 'Алматы', 'url': 'https://api.hh.ru/areas/160'},
  'contacts': None,
  'created_at': '2025-04-30T12:46:36+0300',
  'department': None,
  'employer': {'accredited_it_employer': False,
               'alternate_url': 'https://hh.ru/employer/9574451',
               'employer_rating': None,
               'id': '9574451',
               'logo_urls': {'240': 'https://img.hhcdn.ru/employer-logo/5853574.png',
                             '90': 'https://img.hhcdn.ru/employer-logo/5853573.png',
                             'original': 'https://img.hhcdn.ru/employer-logo-original/1058233.png'},   
               'name': 'Improvado KZ',
               'trusted': True,
               'url': 'https://api.hh.ru/employers/9574451',
               'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=9574451'},
  'employment': {'id': 'full', 'name': 'Полная занятость'},
  'employment_form': {'id': 'FULL', 'name': 'Полная'},
  'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
  'fly_in_fly_out_duration': [],
  'has_test': False,
  'id': '120111330',
  'insider_interview': None,
  'internship': False,
  'is_adv_vacancy': False,
  'name': 'Junior Python Developer',
  'night_shifts': False,
  'premium': False,
  'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}],
  'published_at': '2025-04-30T12:46:36+0300',
  'relations': [],
  'response_letter_required': False,
  'response_url': None,
  'salary': None,
  'salary_range': None,
  'schedule': {'id': 'remote', 'name': 'Удаленная работа'},
  'show_contacts': False,
  'show_logo_in_search': None,
  'snippet': {'requirement': 'Basic knowledge of '
                             '<highlighttext>Python</highlighttext> or 1 year '
                             'in a role focused on '
                             '<highlighttext>Python</highlighttext> backend '
                             '<highlighttext>development</highlighttext> '
                             '(perfectly with Django framework). ',
              'responsibility': 'Participate in code reviews and contribute to '
                                'overall codebase improvements. Participate in '
                                'Agile '
                                '<highlighttext>development</highlighttext> '
                                'methodology, including daily stand-ups, '
                                'sprint...'},
  'sort_point_distance': None,
  'type': {'id': 'open', 'name': 'Открытая'},
  'url': 'https://api.hh.ru/vacancies/120111330?host=hh.ru',
  'work_format': [{'id': 'REMOTE', 'name': 'Удалённо'}],
  'work_schedule_by_days': [{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}],
  'working_days': [],
  'working_hours': [{'id': 'HOURS_8', 'name': '8\xa0часов'}],
  'working_time_intervals': [],
  'working_time_modes': []},
 {'accept_incomplete_resumes': True,
  'accept_temporary': False,
  'address': {'building': '26/1',
              'city': 'Алматы',
              'description': None,
              'id': '16504789',
              'lat': 43.232296,
              'lng': 76.923259,
              'metro': None,
              'metro_stations': [],
              'raw': 'Алматы, бульвар Бухар Жырау, 26/1',
              'street': 'бульвар Бухар Жырау'},
  'adv_context': None,
  'adv_response_url': None,
  'alternate_url': 'https://hh.ru/vacancy/118711736',
  'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=118711736',
  'archived': False,
  'area': {'id': '160', 'name': 'Алматы', 'url': 'https://api.hh.ru/areas/160'},
  'contacts': None,
  'created_at': '2025-04-23T12:52:10+0300',
  'department': None,
  'employer': {'accredited_it_employer': False,
               'alternate_url': 'https://hh.ru/employer/5031522',
               'employer_rating': None,
               'id': '5031522',
               'logo_urls': {'240': 'https://img.hhcdn.ru/employer-logo/7275253.png',
                             '90': 'https://img.hhcdn.ru/employer-logo/7275252.png',
                             'original': 'https://img.hhcdn.ru/employer-logo-original/1413898.png'},   
               'name': 'Autodata',
               'trusted': True,
               'url': 'https://api.hh.ru/employers/5031522',
               'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=5031522'},
  'employment': {'id': 'full', 'name': 'Полная занятость'},
  'employment_form': {'id': 'FULL', 'name': 'Полная'},
  'experience': {'id': 'noExperience', 'name': 'Нет опыта'},
  'fly_in_fly_out_duration': [],
  'has_test': False,
  'id': '118711736',
  'insider_interview': None,
  'internship': True,
  'is_adv_vacancy': False,
  'name': 'Web-программист - стажер',
  'night_shifts': False,
  'premium': False,
  'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}],
  'published_at': '2025-04-23T12:52:10+0300',
  'relations': [],
  'response_letter_required': False,
  'response_url': None,
  'salary': None,
  'salary_range': None,
  'schedule': {'id': 'fullDay', 'name': 'Полный день'},
  'show_contacts': False,
  'show_logo_in_search': None,
  'snippet': {'requirement': 'Carfast- Первый онлайн авто аукцион в '
                             'Казахстане. Доброжелательный и целеустремленный '
                             'командный игрок. Принимаете верные решения в '
                             'критических ситуациях. ',
              'responsibility': 'Лучшая система аналитики товаров на Kaspi. '
                                'Fastbot - Телеграм бот для поиска авто. Ну и '
                                'есть конечно же такие проекты, как...'},
  'sort_point_distance': None,
  'type': {'id': 'open', 'name': 'Открытая'},
  'url': 'https://api.hh.ru/vacancies/118711736?host=hh.ru',
  'work_format': [],
  'work_schedule_by_days': [{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}],
  'working_days': [],
  'working_hours': [{'id': 'HOURS_8', 'name': '8\xa0часов'}],
  'working_time_intervals': [],
  'working_time_modes': []},
 {'accept_incomplete_resumes': False,
  'accept_temporary': False,
  'address': None,
  'adv_context': None,
  'adv_response_url': None,
  'alternate_url': 'https://hh.ru/vacancy/120017270',
  'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=120017270',
  'archived': False,
  'area': {'id': '1', 'name': 'Москва', 'url': 'https://api.hh.ru/areas/1'},
  'contacts': None,
  'created_at': '2025-04-28T10:34:56+0300',
  'department': None,
  'employer': {'accredited_it_employer': False,
               'alternate_url': 'https://hh.ru/employer/11587032',
               'employer_rating': {'reviews_count': None, 'total_rating': '0'},
               'id': '11587032',
               'logo_urls': {'240': 'https://img.hhcdn.ru/employer-logo/7222520.png',
                             '90': 'https://img.hhcdn.ru/employer-logo/7222519.png',
                             'original': 'https://img.hhcdn.ru/employer-logo-original/1400687.png'},   
               'name': 'Кооп',
               'trusted': True,
               'url': 'https://api.hh.ru/employers/11587032',
               'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=11587032'},
  'employment': {'id': 'full', 'name': 'Полная занятость'},
  'employment_form': {'id': 'FULL', 'name': 'Полная'},
  'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'},
  'fly_in_fly_out_duration': [],
  'has_test': False,
  'id': '120017270',
  'insider_interview': None,
  'internship': False,
  'is_adv_vacancy': False,
  'name': 'Senior Frontend Developer / Старший фронтенд-разработчик',
  'night_shifts': False,
  'premium': False,
  'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}],
  'published_at': '2025-04-28T10:34:56+0300',
  'relations': [],
  'response_letter_required': False,
  'response_url': None,
  'salary': {'currency': 'RUR', 'from': 200000, 'gross': True, 'to': 250000},
  'salary_range': {'currency': 'RUR',
                   'frequency': {'id': 'TWICE_PER_MONTH',
                                 'name': 'Два раза в\xa0месяц'},
                   'from': 200000,
                   'gross': True,
                   'mode': {'id': 'MONTH', 'name': 'За\xa0месяц'},
                   'to': 250000},
  'schedule': {'id': 'remote', 'name': 'Удаленная работа'},
  'show_contacts': True,
  'show_logo_in_search': None,
  'snippet': {'requirement': 'Опыт коммерческой разработки на React от 3 лет. '
                             'Глубокое знание TypeScript. Опыт работы с '
                             'Material UI или аналогичными UI-библиотеками. ',
              'responsibility': 'Разработка чата для коммуникации между '
                                'заказчиками и исполнителями. Написание '
                                'unit-тестов и интеграционных тестов. '
                                'Проведение код-ревью для других '
                                '<highlighttext>разработчиков</highlighttext>.'},
  'sort_point_distance': None,
  'type': {'id': 'open', 'name': 'Открытая'},
  'url': 'https://api.hh.ru/vacancies/120017270?host=hh.ru',
  'work_format': [{'id': 'REMOTE', 'name': 'Удалённо'}],
  'work_schedule_by_days': [{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}],
  'working_days': [],
  'working_hours': [{'id': 'HOURS_8', 'name': '8\xa0часов'}],
  'working_time_intervals': [],
  'working_time_modes': []},
 {'accept_incomplete_resumes': False,
  'accept_temporary': False,
  'address': {'building': '54',
              'city': 'Ташкент',
              'description': None,
              'id': '17278632',
              'lat': 41.31704599922101,
              'lng': 69.33990010185167,
              'metro': None,
              'metro_stations': [],
              'raw': 'Ташкент, улица Ломоносова, 54',
              'street': 'улица Ломоносова'},
  'adv_context': None,
  'adv_response_url': None,
  'alternate_url': 'https://hh.ru/vacancy/120168453',
  'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=120168453',
  'archived': False,
  'area': {'id': '2759',
           'name': 'Ташкент',
           'url': 'https://api.hh.ru/areas/2759'},
  'contacts': None,
  'created_at': '2025-05-02T11:43:44+0300',
  'department': None,
  'employer': {'accredited_it_employer': False,
               'alternate_url': 'https://hh.ru/employer/11719146',
               'employer_rating': None,
               'id': '11719146',
               'logo_urls': {'240': 'https://img.hhcdn.ru/employer-logo/7108343.png',
                             '90': 'https://img.hhcdn.ru/employer-logo/7108342.png',
                             'original': 'https://img.hhcdn.ru/employer-logo-original/1372110.png'},   
               'name': 'Grand Invest',
               'trusted': True,
               'url': 'https://api.hh.ru/employers/11719146',
               'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=11719146'},
  'employment': {'id': 'full', 'name': 'Полная занятость'},
  'employment_form': {'id': 'FULL', 'name': 'Полная'},
  'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'},
  'fly_in_fly_out_duration': [],
  'has_test': False,
  'id': '120168453',
  'insider_interview': None,
  'internship': False,
  'is_adv_vacancy': False,
  'name': 'Backend-разработчик (Python/Java)',
  'night_shifts': False,
  'premium': False,
  'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}],
  'published_at': '2025-05-02T11:43:44+0300',
  'relations': [],
  'response_letter_required': False,
  'response_url': None,
  'salary': {'currency': 'UZS', 'from': 5000000, 'gross': True, 'to': 15000000},
  'salary_range': {'currency': 'UZS',
                   'frequency': {'id': 'TWICE_PER_MONTH',
                                 'name': 'Два раза в\xa0месяц'},
                   'from': 5000000,
                   'gross': True,
                   'mode': {'id': 'MONTH', 'name': 'За\xa0месяц'},
                   'to': 15000000},
  'schedule': {'id': 'fullDay', 'name': 'Полный день'},
  'show_contacts': True,
  'show_logo_in_search': None,
  'snippet': {'requirement': 'Глубокие знания и уверенный опыт работы с '
                             '<highlighttext>Python</highlighttext> (Django) '
                             'ИЛИ Java (Spring). Отличное понимание принципов '
                             'ООП. Опыт работы с Websockets. ',
              'responsibility': 'Разработка и поддержка масштабируемой и '
                                'надежной серверной части веб-приложений на '
                                '<highlighttext>Python</highlighttext> '
                                '(Django) или Java (Spring). Проектирование, '
                                'реализация и оптимизация...'},
  'sort_point_distance': None,
  'type': {'id': 'open', 'name': 'Открытая'},
  'url': 'https://api.hh.ru/vacancies/120168453?host=hh.ru',
  'work_format': [{'id': 'ON_SITE', 'name': 'На\xa0месте работодателя'}],
  'work_schedule_by_days': [{'id': 'SIX_ON_ONE_OFF', 'name': '6/1'}],
  'working_days': [],
  'working_hours': [{'id': 'HOURS_9', 'name': '9 часов'}],
  'working_time_intervals': [],
  'working_time_modes': []},
 {'accept_incomplete_resumes': False,
  'accept_temporary': False,
  'address': {'building': None,
              'city': 'Алматы',
              'description': None,
              'id': '15623573',
              'lat': 43.230588,
              'lng': 76.946031,
              'metro': {'lat': 43.242548,
                        'line_id': '64',
                        'line_name': 'Первая',
                        'lng': 76.949588,
                        'station_id': '64.433',
                        'station_name': 'Абая'},
              'metro_stations': [{'lat': 43.242548,
                                  'line_id': '64',
                                  'line_name': 'Первая',
                                  'lng': 76.949588,
                                  'station_id': '64.433',
                                  'station_name': 'Абая'}],
              'raw': 'Алматы, комплекс Нурлы-Тау',
              'street': 'комплекс Нурлы-Тау'},
  'adv_context': None,
  'adv_response_url': None,
  'alternate_url': 'https://hh.ru/vacancy/120166577',
  'apply_alternate_url': 'https://hh.ru/applicant/vacancy_response?vacancyId=120166577',
  'archived': False,
  'area': {'id': '160', 'name': 'Алматы', 'url': 'https://api.hh.ru/areas/160'},
  'contacts': None,
  'created_at': '2025-05-02T09:01:53+0300',
  'department': None,
  'employer': {'accredited_it_employer': False,
               'alternate_url': 'https://hh.ru/employer/5056141',
               'employer_rating': {'reviews_count': 1, 'total_rating': '5'},
               'id': '5056141',
               'logo_urls': {'240': 'https://img.hhcdn.ru/employer-logo/3637060.jpeg',
                             '90': 'https://img.hhcdn.ru/employer-logo/3637059.jpeg',
                             'original': 'https://img.hhcdn.ru/employer-logo-original/799043.jpeg'},   
               'name': 'Faceplate',
               'trusted': True,
               'url': 'https://api.hh.ru/employers/5056141',
               'vacancies_url': 'https://api.hh.ru/vacancies?employer_id=5056141'},
  'employment': {'id': 'full', 'name': 'Полная занятость'},
  'employment_form': {'id': 'FULL', 'name': 'Полная'},
  'experience': {'id': 'between3And6', 'name': 'От 3 до 6 лет'},
  'fly_in_fly_out_duration': [],
  'has_test': False,
  'id': '120166577',
  'insider_interview': None,
  'internship': False,
  'is_adv_vacancy': False,
  'name': 'Frontend-разработчик',
  'night_shifts': False,
  'premium': False,
  'professional_roles': [{'id': '96', 'name': 'Программист, разработчик'}],
  'published_at': '2025-05-02T09:01:53+0300',
  'relations': [],
  'response_letter_required': False,
  'response_url': None,
  'salary': {'currency': 'KZT', 'from': 400, 'gross': True, 'to': 800},
  'salary_range': {'currency': 'KZT',
                   'frequency': None,
                   'from': 400,
                   'gross': True,
                   'mode': {'id': 'MONTH', 'name': 'За\xa0месяц'},
                   'to': 800},
  'schedule': {'id': 'fullDay', 'name': 'Полный день'},
  'show_contacts': True,
  'show_logo_in_search': None,
  'snippet': {'requirement': 'Опыт работы с Linux и репозиториями Git. Знание '
                             'языков программирования для backend (GoLang, '
                             '<highlighttext>Python</highlighttext>, Java, '
                             'Erlang, Elixir) будет вашим преимуществом.',
              'responsibility': 'Инновации: Участвуйте в разработке '
                                'современных систем автоматизации, используя '
                                'новейшие технологии.'},
  'sort_point_distance': None,
  'type': {'id': 'open', 'name': 'Открытая'},
  'url': 'https://api.hh.ru/vacancies/120166577?host=hh.ru',
  'work_format': [{'id': 'ON_SITE', 'name': 'На\xa0месте работодателя'}],
  'work_schedule_by_days': [{'id': 'FIVE_ON_TWO_OFF', 'name': '5/2'}],
  'working_days': [],
  'working_hours': [{'id': 'HOURS_8', 'name': '8\xa0часов'}],
  'working_time_intervals': [],
  'working_time_modes': []}]